package com.netknife.tools.portradar.check;

import com.netknife.common.dto.CheckStatus;

import java.util.List;

/**
 * Lista curada de puertos comunes a escanear, en vez del rango completo
 * 1-65535: es rapida (segundos, no minutos) y cada puerto tiene una traduccion
 * a lenguaje llano ya preparada, que es el objetivo real de esta herramienta
 * frente a un escaner tipo Nmap crudo.
 */
public final class CuratedPortCatalog {

    private static final List<PortDefinition> PORTS = List.of(
            new PortDefinition(21, "FTP",
                    "FTP transmite el usuario y la contrasena sin cifrar: cualquiera en la misma red puede robarlos.",
                    CheckStatus.PELIGRO),
            new PortDefinition(22, "SSH",
                    "SSH es seguro, pero si es accesible desde internet recibe intentos de acceso constantes. Usa una contrasena fuerte o claves.",
                    CheckStatus.ATENCION),
            new PortDefinition(23, "Telnet",
                    "Telnet no cifra nada, ni siquiera la contrasena. Es un protocolo obsoleto e inseguro.",
                    CheckStatus.PELIGRO),
            new PortDefinition(25, "SMTP",
                    "Puerto de envio de correo. Si no esta bien configurado, puede usarse para enviar spam en tu nombre.",
                    CheckStatus.ATENCION),
            new PortDefinition(53, "DNS",
                    "Servidor DNS. Si es accesible desde fuera de tu red, puede usarse para ataques de amplificacion contra terceros.",
                    CheckStatus.ATENCION),
            new PortDefinition(80, "HTTP",
                    "Servidor web sin cifrar. Normal si es tu router o una app local, pero los datos viajan sin proteger.",
                    CheckStatus.OK),
            new PortDefinition(110, "POP3",
                    "Correo POP3 sin cifrar: las credenciales pueden viajar en claro.",
                    CheckStatus.ATENCION),
            new PortDefinition(111, "RPC",
                    "Servicio RPC de Unix/Linux. Rara vez necesita estar accesible desde fuera del equipo.",
                    CheckStatus.ATENCION),
            new PortDefinition(135, "MSRPC",
                    "RPC de Windows. Ha sido la puerta de entrada de varios gusanos historicos; no deberia estar expuesto.",
                    CheckStatus.PELIGRO),
            new PortDefinition(139, "NetBIOS",
                    "Comparticion de archivos antigua de Windows. Puede filtrar el nombre del equipo y recursos compartidos.",
                    CheckStatus.ATENCION),
            new PortDefinition(143, "IMAP",
                    "Correo IMAP sin cifrar: las credenciales pueden viajar en claro.",
                    CheckStatus.ATENCION),
            new PortDefinition(161, "SNMP",
                    "Gestion remota de dispositivos de red. Con la contrasena de fabrica (a menudo 'public') cualquiera puede leer o cambiar la configuracion.",
                    CheckStatus.PELIGRO),
            new PortDefinition(389, "LDAP",
                    "Directorio de usuarios sin cifrar.",
                    CheckStatus.ATENCION),
            new PortDefinition(443, "HTTPS",
                    "Servidor web cifrado. Es lo esperado y seguro.",
                    CheckStatus.OK),
            new PortDefinition(445, "SMB",
                    "Comparticion de archivos de Windows. Ha sido el vector de ransomware mas explotado de la ultima decada; no deberia ser accesible desde fuera de tu red.",
                    CheckStatus.PELIGRO),
            new PortDefinition(465, "SMTPS",
                    "Envio de correo cifrado.",
                    CheckStatus.OK),
            new PortDefinition(512, "rexec",
                    "Ejecucion remota de comandos sin cifrar. Protocolo obsoleto de decadas atras.",
                    CheckStatus.PELIGRO),
            new PortDefinition(513, "rlogin",
                    "Login remoto sin cifrar. Protocolo obsoleto e inseguro.",
                    CheckStatus.PELIGRO),
            new PortDefinition(514, "rsh",
                    "Shell remota sin cifrar. Protocolo obsoleto e inseguro.",
                    CheckStatus.PELIGRO),
            new PortDefinition(587, "SMTP (envio autenticado)",
                    "Envio de correo autenticado, el estandar actual.",
                    CheckStatus.OK),
            new PortDefinition(631, "IPP (impresoras)",
                    "Comparticion de impresoras. Puede exponer el nombre y la configuracion de tu impresora.",
                    CheckStatus.ATENCION),
            new PortDefinition(993, "IMAPS",
                    "Correo IMAP cifrado.",
                    CheckStatus.OK),
            new PortDefinition(995, "POP3S",
                    "Correo POP3 cifrado.",
                    CheckStatus.OK),
            new PortDefinition(1433, "SQL Server",
                    "Base de datos SQL Server. Si es accesible desde fuera, es un objetivo directo de ataques.",
                    CheckStatus.PELIGRO),
            new PortDefinition(1521, "Oracle",
                    "Base de datos Oracle. No deberia estar accesible desde fuera de tu red.",
                    CheckStatus.PELIGRO),
            new PortDefinition(1723, "PPTP (VPN)",
                    "VPN PPTP, un protocolo con vulnerabilidades conocidas y cifrado roto desde hace anos.",
                    CheckStatus.PELIGRO),
            new PortDefinition(2049, "NFS",
                    "Comparticion de archivos de Unix/Linux. Puede exponer archivos si no esta bien configurada.",
                    CheckStatus.ATENCION),
            new PortDefinition(2375, "Docker (API)",
                    "API de Docker sin autenticacion. Si esta accesible, cualquiera puede tomar el control total del equipo.",
                    CheckStatus.PELIGRO),
            new PortDefinition(27017, "MongoDB",
                    "Base de datos MongoDB. Una causa muy comun de fugas masivas de datos cuando queda accesible sin contrasena.",
                    CheckStatus.PELIGRO),
            new PortDefinition(3000, "Servidor de desarrollo",
                    "Puerto tipico de un servidor de desarrollo. No deberia estar accesible fuera de tu equipo.",
                    CheckStatus.ATENCION),
            new PortDefinition(3306, "MySQL",
                    "Base de datos MySQL. Si es accesible desde fuera, es un objetivo directo de ataques.",
                    CheckStatus.PELIGRO),
            new PortDefinition(3389, "RDP (Escritorio remoto)",
                    "Escritorio remoto de Windows. Uno de los puntos de entrada mas comunes en ataques de ransomware.",
                    CheckStatus.PELIGRO),
            new PortDefinition(5000, "Servidor de desarrollo",
                    "Puerto tipico de un servidor de desarrollo. No deberia estar accesible fuera de tu equipo.",
                    CheckStatus.ATENCION),
            new PortDefinition(5432, "PostgreSQL",
                    "Base de datos PostgreSQL. Si es accesible desde fuera, es un objetivo directo de ataques.",
                    CheckStatus.PELIGRO),
            new PortDefinition(5900, "VNC",
                    "Escritorio remoto VNC. Muchas instalaciones no piden contrasena o usan una muy debil por defecto.",
                    CheckStatus.PELIGRO),
            new PortDefinition(5985, "WinRM (HTTP)",
                    "Gestion remota de Windows sin cifrar.",
                    CheckStatus.PELIGRO),
            new PortDefinition(5986, "WinRM (HTTPS)",
                    "Gestion remota de Windows cifrada. Sigue siendo sensible si esta expuesta a internet.",
                    CheckStatus.ATENCION),
            new PortDefinition(6379, "Redis",
                    "Base de datos Redis. Por defecto no pide contrasena, una de las causas mas comunes de servidores comprometidos.",
                    CheckStatus.PELIGRO),
            new PortDefinition(8080, "HTTP alternativo",
                    "Servidor web alternativo sin cifrar, comun en paneles de administracion.",
                    CheckStatus.ATENCION),
            new PortDefinition(8443, "HTTPS alternativo",
                    "Servidor web alternativo cifrado.",
                    CheckStatus.OK),
            new PortDefinition(8888, "Puerto alternativo",
                    "Puerto usado a menudo por paneles de administracion o herramientas de desarrollo. Revisa que hay detras.",
                    CheckStatus.ATENCION),
            new PortDefinition(9200, "Elasticsearch",
                    "Base de datos Elasticsearch. Sin autenticacion por defecto, causa frecuente de fugas de datos masivas.",
                    CheckStatus.PELIGRO),
            new PortDefinition(9090, "Prometheus",
                    "Panel de metricas. Puede exponer informacion interna de tus sistemas.",
                    CheckStatus.ATENCION)
    );

    private CuratedPortCatalog() {
    }

    public static List<PortDefinition> all() {
        return PORTS;
    }
}
